# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

general {
  resize_on_border = false
}
input {
	sensitivity = 0.4

  touchpad {
    scroll_factor = 2
  }
}
