# See https://wiki.hyprland.org/Configuring/Binds/
# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds
bindld = ,Print, Screenshot, exec, grim -g "$(slurp)" - | swappy -f - # Screenshot to swappy

bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds


unbind = SUPER, W
bind = SUPER, W, exec, google-chrome-stable --ozone-platform=wayland --disable-features=WaylandWpColorManagerV1 --enable-features=WaylandWindowDecorations --enable-accelerated-video-decode --enable-accelerated-2d-canvas


#!
##! Window Snapping
# Primary controls - navigate and the script figures out the layout
bind = SUPER+ALT, K, exec, ~/.config/hypr/custom/scripts/snap_hypr.sh up # Move/snap up
bind = SUPER+ALT, J, exec, ~/.config/hypr/custom/scripts/snap_hypr.sh down # Move/snap down
bind = SUPER+ALT, H, exec, ~/.config/hypr/custom/scripts/snap_hypr.sh left # Move/snap left
bind = SUPER+ALT, L, exec, ~/.config/hypr/custom/scripts/snap_hypr.sh right # Move/snap right

# Arrow key alternatives
bind = SUPER+ALT, UP, exec, ~/.config/hypr/custom/scripts/snap_hypr.sh up # Move/snap up
bind = SUPER+ALT, DOWN, exec, ~/.config/hypr/custom/scripts/snap_hypr.sh down # Move/snap down
bind = SUPER+ALT, LEFT, exec, ~/.config/hypr/custom/scripts/snap_hypr.sh left # Move/snap left
bind = SUPER+ALT, RIGHT, exec, ~/.config/hypr/custom/scripts/snap_hypr.sh right # Move/snap right

# Launch floating fuzzy package installer
bind = SUPER, P, exec, kitty --class pkgpicker -e ~/.config/hypr/custom/scripts/fuzzy-pkg.sh install
bind = Ctrl+SUPER, P, exec, kitty --class pkgpicker -e ~/.config/hypr/custom/scripts/fuzzy-pkg.sh remove

# Keybind for dropdown terminal
bind = CTRL, 1, exec, ~/.config/hypr/custom/scripts/dropterm.sh
