# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Package picker rules
windowrule = match:class ^(pkgpicker)$, float on
windowrule = match:class ^(pkgpicker)$, center on
windowrule = match:class ^(pkgpicker)$, size 1000 600
windowrule = match:class ^(pkgpicker)$, border_size 0

# Dropdown terminal window rules
windowrule = match:class ^(kitty-dropdown)$, float on
windowrule = match:class ^(kitty-dropdown)$, size (monitor_w*.85) (monitor_h*.60)
windowrule = match:class ^(kitty-dropdown)$, move (monitor_w*.075) (monitor_h*.05)
windowrule = match:class ^(kitty-dropdown)$, animation popin 80%
windowrule = match:class ^(kitty-dropdown)$, workspace special:dropdown silent
windowrule = match:class ^(kitty-dropdown)$, dim_around on
