function extract
    if test (count $argv) -eq 0; or test "$argv[1]" = "-h"; or test "$argv[1]" = "--help"
        echo "Usage: extract <archive> [directory]"
        echo "Example: extract presentation.zip."
        echo "Valid archive types are:"
        echo "tar.bz2, tar.gz, tar.xz, tar, bz2, gz, tbz2,"
        echo "tbz, tgz, lzo, rar, zip, 7z, xz, txz, lzma and tlz"
        return
    end

    switch "$argv[1]"
        case "*.tar.bz2" "*.tbz2" "*.tbz"
            tar xvjf "$argv[1]"
        case "*.tgz"
            tar zxvf "$argv[1]"
        case "*.tar.gz"
            tar xvzf "$argv[1]"
        case "*.tar.xz"
            tar xvJf "$argv[1]"
        case "*.tar"
            tar xvf "$argv[1]"
        case "*.rar"
            7z x "$argv[1]"
        case "*.zip"
            unzip "$argv[1]"
        case "*.7z"
            7z x "$argv[1]"
        case "*.lzo"
            lzop -d "$argv[1]"
        case "*.gz"
            gunzip "$argv[1]"
        case "*.bz2"
            bunzip2 "$argv[1]"
        case "*.Z"
            uncompress "$argv[1]"
        case "*.xz" "*.txz" "*.lzma" "*.tlz"
            xz -d "$argv[1]"
        case "*"
            echo "Sorry, '$argv[1]' could not be decompressed."
    end
end
